# Generated by Django 6.0.2 on 2026-02-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_propertyimage_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('booked', 'Booked')], default='available', max_length=20),
        ),
    ]
