# Generated by Django 4.2.28 on 2026-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_publish_default_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('TZS', 'TZS')], default='TZS', max_length=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
